### ISSUE TITLE
compilation under Ubuntu 14.04 and MATLAB R2015b

### ISSUE THREAD

**Issue by michalkvasnicka** [DavidFCrouse/Tracker-Component-Library#1]
I tried to compile whole Tracker-Component-Library by CompileCLibraries function. But there are a lot of problems and incompatibilities. 

Trivial troubles with // in source code was removed by adding of 'CFLAGS="\$CFLAGS -std=c99"' to mex commands in CompileCLibraries function. See attached file.

But the next problem is more difficult (at least for me, I am not C expert):

> In CompileCLibraries_Linux (line 42) 
/usr/bin/g++ -c -U__STDC_UTF_16__   -D_GNU_SOURCE -DMATLAB_MEX_FILE  -I./ -I./3rd_Party_Code/GeographicLib-1.43/include -I"./Container Classes/Shared C++ Code/" -I"./Mathematical Functions/Shared C++ Code/"  -I"/usr/local/MATLAB/R2015b/extern/include" -I"/usr/local/MATLAB/R2015b/simulink/include" -ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++11 -O -DNDEBUG /home/kva/tmp/Tracker-Component-Library-master/./Navigation/indirectGeodeticProb.cpp -o /tmp/mex_2293036706664339_13060/indirectGeodeticProb.o
Error using mex
In file included from /home/kva/tmp/Tracker-Component-Library-master/./Navigation/indirectGeodeticProb.cpp:65:0:
./MexValidation.h: In function ‘size_t* copySizeTArrayFromMatlab(const mxArray*, size_t*)’:
./MexValidation.h:1171:61: error: ‘memcpy’ was not declared in this scope
                 memcpy(retVal,mexData,numEl*sizeof(uint32_T));
                                                             ^
./MexValidation.h:1199:61: error: ‘memcpy’ was not declared in this scope
                 memcpy(retVal,mexData,numEl*sizeof(uint64_T));
                                                             ^
./MexValidation.h: In function ‘mxArray* doubleMat2Matlab(const double*, size_t, size_t)’:
./MexValidation.h:1476:52: error: ‘memcpy’ was not declared in this scope
     memcpy(dataPtr,arr,numRow*numCol*sizeof(double));
                                                    ^
In file included from /home/kva/tmp/Tracker-Component-Library-master/./Navigation/indirectGeodeticProb.cpp:65:0:
./MexValidation.h: In function ‘mxArray* unsignedSizeMat2Matlab(const size_t*, size_t, size_t)’:
./MexValidation.h:1604:52: error: ‘memcpy’ was not declared in this scope
     memcpy(dataPtr,arr,numRow*numCol*sizeof(size_t));
                                                    ^
./MexValidation.h: In function ‘mxArray* signedSizeMat2Matlab(const ptrdiff_t*, size_t, size_t)’:
./MexValidation.h:1616:55: error: ‘memcpy’ was not declared in this scope
     memcpy(dataPtr,arr,numRow*numCol*sizeof(ptrdiff_t));
                                                       ^
In file included from ./Mathematical Functions/Shared C++ Code/mathFuncs.hpp:13:0,
                 from /home/kva/tmp/Tracker-Component-Library-master/./Navigation/indirectGeodeticProb.cpp:70:
./Container Classes/Shared C++ Code/ClusterSetCPP.hpp: In member function ‘void ClusterSetCPP<T>::initWithClusterSizes(const
size_t*, size_t)’:
./Container Classes/Shared C++ Code/ClusterSetCPP.hpp:66:66: error: there are no arguments to ‘memcpy’ that depend on a template
parameter, so a declaration of ‘memcpy’ must be available [-fpermissive]
         memcpy(clusterSizes,clustSizes,numClusters*sizeof(size_t));
                                                                  ^
./Container Classes/Shared C++ Code/ClusterSetCPP.hpp:66:66: note: (if you use ‘-fpermissive’, G++ will accept your code, but
allowing the use of an undeclared name is deprecated)

Error in CompileCLibraries_Linux (line 42)
mex('-v','-largeArrayDims','-U__STDC_UTF_16__','CFLAGS="\$CFLAGS
-std=c99"','-outdir','./0_Compiled_Code/','-I./','-I./3rd_Party_Code/GeographicLib-1.43/include','-I./Container Classes/Shared C++
Code/','-I./Mathematical Functions/Shared C++ Code/','./Navigation/indirectGeodeticProb.cpp','./Mathematical Functions/Shared C++
Code/wrapRangeCPP.cpp','./3rd_Party_Code/GeographicLib-1.43/src/Geodesic.cpp','./3rd_Party_Code/GeographicLib-1.43/src/GeodesicExact.cpp','./3rd_Party_Code/GeographicLib-1.43/src/GeodesicLine.cpp','./3rd_Party_Code/GeographicLib-1.43/src/GeodesicLineExact.cpp','./3rd_Party_Code/GeographicLib-1.43/src/EllipticFunction.cpp','./3rd_Party_Code/GeographicLib-1.43/src/Math.cpp','./3rd_Party_Code/GeographicLib-1.43/src/GeodesicExactC4.cpp');

**Comment by michalkvasnicka** [comment]
I found other serious troubles regarding of recompilation on Linux:

- absence of #include <cstring> in MexValidation.h ... a lot of problems with memcpy

But simple add of #include <cstring> to #ifdef __cplusplus block in MexValidation.h does not solve all problems.

**Comment by michalkvasnicka** [comment]
I found another another errors during Linux (Ubuntu) compilation:

0. Add 'CFLAGS="\$CFLAGS -std=c99"' to all mex command at CompileCLibraries 
(use C++ style comments, which start with ...//...) see http://stackoverflow.com/questions/17977442/mex-generates-error-for-while-compiling-c-code-in-linux

1. Add #include <cstring> to ShortestPathCPP.cpp (memcpy)

2. Add #include <cstddef> and #include <algorithm> to ClusterSetCPP.hpp (memcpy and sort)

3. Add #include <cstddef> to ais.h (ais6.cpp:16:9: error: ‘ptrdiff_t’ does not name a type)

4. Add -fPIC compiler option to Makefile-custom 
(/usr/bin/g++ -c -U__STDC_UTF_16__   -D_GNU_SOURCE -DMATLAB_MEX_FILE  -I./3rd_Party_Code/libais/ -I./  -I"/usr/local/MATLAB/R2015b/extern/include" -I"/usr/local/MATLAB/R2015b/simulink/include" -ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++11 -O -DNDEBUG /data/kva/Dropbox/Work/LPopt2/RankedAssignments/Tracker-Component-Library/Tracker-Component-Library-master2/./Transponders/decodeAISString.cpp -o /tmp/mex_17307769890566_12718/decodeAISString.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/usr/local/MATLAB/R2015b/extern/lib/glnxa64/mexFunction.map" /tmp/mex_17307769890566_12718/decodeAISString.o   ./0_Compiled_Code/libais.a  -Wl,-rpath-link,/usr/local/MATLAB/R2015b/bin/glnxa64 -L"/usr/local/MATLAB/R2015b/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -o /data/kva/Dropbox/Work/LPopt2/RankedAssignments/Tracker-Component-Library/Tracker-Component-Library-master2/./0_Compiled_Code//decodeAISString.mexa64
Error using mex
/usr/bin/ld: ./0_Compiled_Code/libais.a(ais.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared
object; recompile with -fPIC
./0_Compiled_Code/libais.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status)

5. Add -fPIC compiler option to makefile
(/usr/bin/gcc -c -U__STDC_UTF_16__   -D_GNU_SOURCE -DMATLAB_MEX_FILE  -I./3rd_Party_Code/sofa/src/ -I./  -I"/usr/local/MATLAB/R2015b/extern/include" -I"/usr/local/MATLAB/R2015b/simulink/include" \-ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c99 -O -DNDEBUG "/data/kva/Dropbox/Work/LPopt2/RankedAssignments/Tracker-Component-Library/Tracker-Component-Library-master2/./Astronomical Code/changeEpoch.c" -o /tmp/mex_18215113938096_12718/changeEpoch.o
/usr/bin/gcc -pthread -Wl,--no-undefined -Wl,-rpath-link,/usr/local/MATLAB/R2015b/bin/glnxa64 -shared  -O -Wl,--version-script,"/usr/local/MATLAB/R2015b/extern/lib/glnxa64/mexFunction.map" /tmp/mex_18215113938096_12718/changeEpoch.o   ./0_Compiled_Code/libsofa_c.a  -L"/usr/local/MATLAB/R2015b/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -o /data/kva/Dropbox/Work/LPopt2/RankedAssignments/Tracker-Component-Library/Tracker-Component-Library-master2/./0_Compiled_Code//changeEpoch.mexa64
Error using mex
/usr/bin/ld: ./0_Compiled_Code/libsofa_c.a(iauStarpm.o): relocation R_X86_64_PC32 against undefined symbol `sqrt@@GLIBC_2.2.5' can
not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status)

I am not sure if I correct all errors properly (especially errors 3, 4 and 5). So, it is up to you to decide how to correct all problems.

**Comment by DavidFCrouse** [comment]
1, 2 and 3 should be correct now.

I will look at the MICE library prior to the AIS library. I am using NASA’s compile scripts; I will see if I am just missing the LINUX ones.

I might have to use a check for endianness with respect to the AIS library, because it might not work on big-endian machines. However, I have not tested it.

- David Crouse

**Comment by michalkvasnicka** [comment]
After latest commits the compilation on Linux now works without any problem.
