### ISSUE TITLE
MICE library Linux compilation

### ISSUE THREAD

**Issue by michalkvasnicka** [DavidFCrouse/Tracker-Component-Library#3]
There are three MICE library Linux compilation problems:

1. Modern Linux distribution comes without csh-shell (only bash is installed typically), so there should be check of presence of csh and/or csh install hint, because install script makeall.csh is csh-like.  

2. In the ../3rd_Party_Code/mice/ directory have to be created the following subdirectories:
 ./lib/ and ./exe/

3. compile script .mice/mkprodct.csh produce MEX file mice.mexmaci64.mexa64 which should be placed at ./0_Compiled_Code/.. as mice.mexa64 (not mice.mexmaci64.mexa64).

**Comment by DavidFCrouse** [comment]
Git will not maintain empty folders. I put placeholders in the empty folders to solve problem 2.

- David Crouse

**Comment by michalkvasnicka** [comment]
After latest commits the compilation on Linux now works without any problem.
