### ISSUE TITLE
demoSunLocation error (undefined varaiable "rGCRS")

### ISSUE THREAD

**Issue by michalkvasnicka** [DavidFCrouse/Tracker-Component-Library#4]
The  produce the following error:

>> demoSunLocation
Simulating the location of the Sun with and without refraction for an
Observer in Hilo, Hawaii on 1 June 2013 at 15:42 UTC.
 
1) Determining the refraction-free outline of the Sun
Undefined function or variable 'rGCRS'.

Error in solarBodyVec (line 463)
        rITRS=GCRS2ITRS(rGCRS,Jul1,Jul2,deltaTTUT1,xpyp,dXdY);

Error in demoSunLocation (line 37)
[~,rSunITRS]=solarBodyVec(JulUTC1,JulUTC2,'UTC','SUN',0,[obsLoc;0;0;0],'ITRS');

**Comment by DavidFCrouse** [comment]
The problem resulted from renaming things just before it was released. I fixed this issue.

- David Crouse
