### ISSUE TITLE
Windows compileation problem

### ISSUE THREAD

**Issue by michalkvasnicka** [DavidFCrouse/Tracker-Component-Library#5]
Windows 7 pro (64bit) + Visual Studio 2013 C/C++ compiler

Building with 'Microsoft Visual C++ 2013 Professional'.
cl /c /Zp8 /GR /W3 /EHs /nologo /MD /O2 /Oy- /DNDEBUG -U__STDC_UTF_16__   /D_CRT_SECURE_NO_DEPRECATE /D_SCL_SECURE_NO_DEPRECATE /D_SECURE_SCL=0   /DMATLAB_MEX_FILE -I./3rd_Party_Code/libais/ -I./  -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\Program Files\MATLAB\R2015b\simulink\include" C:\Users\Misak\tmp\Tracker-Component-Library-master\Tracker-Component-Library-master\Transponders\decodeAISPosReports2Mat.cpp /FoC:\Users\Misak\AppData\Local\Temp\mex_48271705831070_5256\decodeAISPosReports2Mat.obj
Error using mex
decodeAISPosReports2Mat.cpp
MexValidation.h(1306) : warning C4800: 'mxChar' : forcing value to bool 'true' or 'false' (performance warning)
MexValidation.h(1324) : warning C4800: 'double' : forcing value to bool 'true' or 'false' (performance warning)
MexValidation.h(1333) : warning C4800: 'float' : forcing value to bool 'true' or 'false' (performance warning)
MexValidation.h(1342) : warning C4800: 'int8_T' : forcing value to bool 'true' or 'false' (performance warning)
MexValidation.h(1351) : warning C4800: 'uint8_T' : forcing value to bool 'true' or 'false' (performance warning)
MexValidation.h(1360) : warning C4800: 'int16_T' : forcing value to bool 'true' or 'false' (performance warning)
MexValidation.h(1369) : warning C4800: 'uint16_T' : forcing value to bool 'true' or 'false' (performance warning)
MexValidation.h(1378) : warning C4800: 'int32_T' : forcing value to bool 'true' or 'false' (performance warning)
MexValidation.h(1387) : warning C4800: 'uint32_T' : forcing value to bool 'true' or 'false' (performance warning)
MexValidation.h(1396) : warning C4800: 'int64_T' : forcing value to bool 'true' or 'false' (performance warning)
MexValidation.h(1405) : warning C4800: 'uint64_T' : forcing value to bool 'true' or 'false' (performance warning)
C:\Users\Misak\tmp\Tracker-Component-Library-master\Tracker-Component-Library-master\Transponders\decodeAISPosReports2Mat.cpp(184)
: error C3861: 'max': identifier not found

Error in CompileCLibraries (line 343)
mex('-v','-largeArrayDims','-U__STDC_UTF_16__','-outdir','./0_Compiled_Code/','-I./3rd_Party_Code/libais/','-I./','./Transponders/decodeAISPosReports2Mat.cpp',linkCommands{:})

**Comment by lmillefiori** [comment]
This is a common problem under Windows.
You should be able to fix it adding `#include <windows.h>` or `#include <algorithm>` in `decodeAISPosReports2Mat.cpp`.

**Comment by DavidFCrouse** [comment]
I added #include <algorithm> to get rid of the problem; it is the most platform-independent option without having to explicitly check for whether it is being compiled under Windows.
