### ISSUE TITLE
Matlab version of perm hangon for 1x1 input matrix

### ISSUE THREAD

**Issue by michalkvasnicka** [DavidFCrouse/Tracker-Component-Library#6]
Matlab version of perm function (not MEX version!!!) hangs in while-loop for scalar input:

examples:
perm(2) or perm([2])

should be equal 2

Note: The MEX version works well in this case!

**Comment by michalkvasnicka** [comment]
I propose add to perm.m file the following code:

%Scalar matrices have a permanent of A by definition    
    if numel(A) == 1
        val = A;
        return;
    end

**Comment by DavidFCrouse** [comment]
I pushed the correction.

- David Crouse
